baseurl = "https://sabayon.github.io/community-website/"
languageCode = "en-us"
title = "Sabayon Linux"
canonifyurls = true

sectionPagesMenu = "main"

[menu]
  [[menu.main]]
    identifier = "download"
    name = "Download"
    url = "https://www.sabayon.org/download/"

  [[menu.main]]
    identifier = "press"
    name = "Press"
    url = "https://www.sabayon.org/press/"
